var sysdictData = {
    "propertyStatus": [{
        "value": "停止服务",
        "comment": "业主状态",
        "key": "0"
    }, {
        "value": "正常服务",
        "comment": "业主状态",
        "key": "1"
    }],
    "networkType": [{
        "value": "移动2G",
        "comment": "运营商网络",
        "key": "1"
    }, {
        "value": "移动3G",
        "comment": "运营商网络",
        "key": "2"
    }, {
        "value": "移动4G",
        "comment": "运营商网络",
        "key": "3"
    }, {
        "value": "联通2G",
        "comment": "运营商网络",
        "key": "4"
    }, {
        "value": "联通3G",
        "comment": "运营商网络",
        "key": "5"
    }, {
        "value": "联通4G",
        "comment": "运营商网络",
        "key": "6"
    }, {
        "value": "电信2G",
        "comment": "运营商网络",
        "key": "7"
    }, {
        "value": "电信3G",
        "comment": "运营商网络",
        "key": "8"
    }, {
        "value": "电信4G",
        "comment": "运营商网络",
        "key": "9"
    }],
    "processStatus": [{
        "value": "未处理",
        "comment": "代缴处理状态",
        "key": "01"
    }, {
        "value": "已受理",
        "comment": "代缴处理状态",
        "key": "02"
    }, {
        "value": "已缴费",
        "comment": "代缴处理状态",
        "key": "03"
    }, {
        "value": "缴费失败",
        "comment": "代缴处理状态",
        "key": "04"
    }],
    "payingType": [{
        "value": "水费代缴",
        "comment": "人工代缴缴费类型",
        "key": "01"
    }, {
        "value": "电费代缴",
        "comment": "人工代缴缴费类型",
        "key": "02"
    }, {
        "value": "气费代缴",
        "comment": "人工代缴缴费类型",
        "key": "03"
    }],
    "billStatus": [{
        "value": "未缴",
        "comment": "账单状态",
        "key": "01"
    }, {
        "value": "已缴",
        "comment": "账单状态",
        "key": "02"
    }, {
        "value": "未结清",
        "comment": "账单状态",
        "key": "03"
    }],
    "isCheck": [{
        "value": "否",
        "comment": "是否需要复核（服务控制）",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否需要复核（服务控制）",
        "key": "1"
    }],
    "serviceCenterUploadFile": [{
        "value": "服务中心图片目录",
        "comment": "上传文件目录",
        "key": "serviceCenter/"
    }],
    "receivceChanType": [{
        "value": "短信",
        "comment": "通知渠道",
        "key": "1"
    }, {
        "value": "系统通知",
        "comment": "通知渠道",
        "key": "2"
    }, {
        "value": "微信",
        "comment": "通知渠道",
        "key": "3"
    }, {
        "value": "微博",
        "comment": "通知渠道",
        "key": "4"
    }, {
        "value": "QQ",
        "comment": "通知渠道",
        "key": "5"
    }, {
        "value": "其他",
        "comment": "通知渠道",
        "key": "6"
    }],
    "listCat": [{
        "value": "证件号",
        "comment": "名单类别(黑白名单控制表)",
        "key": "1"
    }, {
        "value": "手机号",
        "comment": "名单类别(黑白名单控制表)",
        "key": "2"
    }, {
        "value": "IP地址",
        "comment": "名单类别(黑白名单控制表)",
        "key": "3"
    }, {
        "value": "客户号",
        "comment": "名单类别(黑白名单控制表)",
        "key": "4"
    }, {
        "value": "公司编号",
        "comment": "名单类别(黑白名单控制表)",
        "key": "5"
    }],
    "isRecordBusJournal": [{
        "value": "否",
        "comment": "是否记录业务流水（服务控制）",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否记录业务流水（服务控制）",
        "key": "1"
    }],
    "controlCycle": [{
        "value": "不限制周期",
        "comment": "抽奖免费次数的控制周期",
        "key": "0"
    }, {
        "value": "按天控制",
        "comment": "抽奖免费次数的控制周期",
        "key": "1"
    }],
    "tiketPurpose": [{
        "value": "抽奖",
        "comment": "卡券用途",
        "key": "01"
    }, {
        "value": "返利",
        "comment": "卡券用途",
        "key": "02"
    }],
    "isDefault": [{
        "value": "否",
        "comment": "是否默认地址",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否默认地址",
        "key": "1"
    }],
    "isPush": [{
        "value": "否",
        "comment": "是否推送",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否推送",
        "key": "1"
    }],
    "redeemType": [{
        "value": "支付宝",
        "comment": "积分兑换类型",
        "key": "alipay"
    }, {
        "value": "Q币",
        "comment": "积分兑换类型",
        "key": "qb"
    }, {
        "value": "优惠券",
        "comment": "积分兑换类型",
        "key": "coupon"
    }, {
        "value": "实物",
        "comment": "积分兑换类型",
        "key": "object"
    }, {
        "value": "话费",
        "comment": "积分兑换类型",
        "key": "phonebill"
    }, {
        "value": "流量",
        "comment": "积分兑换类型",
        "key": "phoneFlow"
    }, {
        "value": "虚拟商品",
        "comment": "积分兑换类型",
        "key": "virtual"
    }, {
        "value": "大转盘",
        "comment": "积分兑换类型",
        "key": "turntable"
    }, {
        "value": "单品抽奖",
        "comment": "积分兑换类型",
        "key": "singleLottery"
    }],
    "promoIsTop": [{
        "value": "否",
        "comment": "置顶标志",
        "key": "0"
    }, {
        "value": "是",
        "comment": "置顶标志",
        "key": "1"
    }],
    "payMethod": [{
        "value": "普通",
        "comment": "人工缴费方式",
        "key": "01"
    }, {
        "value": "加急",
        "comment": "人工缴费方式",
        "key": "02"
    }],
    "shippingType": [{
        "value": "预缴优惠",
        "comment": "预缴优惠类型",
        "key": "0"
    }, {
        "value": "一键缴费",
        "comment": "预缴优惠类型",
        "key": "1"
    }],
    "feedBack": [{
        "value": "功能建议 ",
        "comment": "反馈类型",
        "key": "01"
    }, {
        "value": "体验优化  ",
        "comment": "反馈类型",
        "key": "02"
    }, {
        "value": "其它  ",
        "comment": "反馈类型",
        "key": "03"
    }],
    "productUploadFile": [{
        "value": "产品图片存放目录",
        "comment": "上传文件目录",
        "key": "product/"
    }],
    "housingPurposes": [{
        "value": "居住",
        "comment": "房屋用途",
        "key": "0"
    }, {
        "value": "商铺",
        "comment": "房屋用途",
        "key": "2"
    }],
    "isUse": [{
        "value": "否",
        "comment": "是否启用（接口版本控制）",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否启用（接口版本控制）",
        "key": "1"
    }],
    "yw2": [{
        "value": "yw/logo.png",
        "comment": "公司个性化字典",
        "key": "ywLogo"
    }],
    "prizeType": [{
        "value": "实物奖品",
        "comment": "奖品类型",
        "key": "01"
    }, {
        "value": "虚拟奖品",
        "comment": "奖品类型",
        "key": "02"
    }],
    "isEmplyoee": [{
        "value": "否",
        "comment": "是否员工",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否员工",
        "key": "1"
    }],
    "waitAudit": [{
        "value": "否",
        "comment": "是否需要审核",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否需要审核",
        "key": "1"
    }],
    "systemOs": [{
        "value": "IOS",
        "comment": "系统标识",
        "key": "1"
    }, {
        "value": "android",
        "comment": "系统标识",
        "key": "2"
    }, {
        "value": "WindowsPhone",
        "comment": "系统标识",
        "key": "3"
    }, {
        "value": "PC",
        "comment": "系统标识",
        "key": "4"
    }, {
        "value": "手机网页版",
        "comment": "系统标识",
        "key": "5"
    }],
    "assetsType": [{
        "value": "居住用房",
        "comment": "关联资产类型",
        "key": "0"
    }, {
        "value": "车库",
        "comment": "关联资产类型",
        "key": "1"
    }, {
        "value": "商铺",
        "comment": "关联资产类型",
        "key": "2"
    }, {
        "value": "其他",
        "comment": "关联资产类型",
        "key": "3"
    }],
    "addStatus": [{
        "value": "建设中",
        "comment": "房屋加建状态",
        "key": "0"
    }, {
        "value": "已完工",
        "comment": "房屋加建状态",
        "key": "1"
    }],
    "isSupport": [{
        "value": "否",
        "comment": "是否支持人工代缴",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否支持人工代缴",
        "key": "1"
    }],
    "promotionUploadFile": [{
        "value": "活动信息背景图片目录",
        "comment": "上传文件目录",
        "key": "promotion/"
    }],
    "serviceStatus": [{
        "value": "失败",
        "comment": "服务操作状态",
        "key": "0"
    }, {
        "value": "成功",
        "comment": "服务操作状态",
        "key": "1"
    }, {
        "value": "未完成",
        "comment": "服务操作状态",
        "key": "2"
    }, {
        "value": "已冲正",
        "comment": "服务操作状态",
        "key": "3"
    }],
    "game_state": [{
        "value": "成功 ",
        "comment": "在线缴费状态",
        "key": "1"
    }, {
        "value": "失败 ",
        "comment": "在线缴费状态",
        "key": "9"
    }, {
        "value": "充值中",
        "comment": "在线缴费状态",
        "key": "0"
    }],
    "payStatus": [{
        "value": "交易未明",
        "comment": "缴费状态",
        "key": "00"
    }, {
        "value": "预缴费",
        "comment": "缴费状态",
        "key": "01"
    }, {
        "value": "待复核",
        "comment": "缴费状态",
        "key": "02"
    }, {
        "value": "完成",
        "comment": "缴费状态",
        "key": "03"
    }, {
        "value": "已撤销",
        "comment": "缴费状态",
        "key": "04"
    }, {
        "value": "缴费失败",
        "comment": "缴费状态",
        "key": "05"
    }, {
        "value": "复核失败",
        "comment": "缴费状态",
        "key": "06"
    }],
    "isArreas": [{
        "value": "欠费",
        "comment": "是否欠费",
        "key": "0"
    }, {
        "value": "不欠费",
        "comment": "是否欠费",
        "key": "1"
    }],
    "isRecordJournal": [{
        "value": "否",
        "comment": "是否记录服务流水（服务控制）",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否记录服务流水（服务控制）",
        "key": "1"
    }],
    "userStatus": [{
        "value": "正常",
        "comment": "用户状态",
        "key": "0"
    }, {
        "value": "休眠",
        "comment": "用户状态",
        "key": "1"
    }, {
        "value": "锁定",
        "comment": "用户状态",
        "key": "2"
    }, {
        "value": "未注册",
        "comment": "用户注册状态",
        "key": "0"
    }, {
        "value": "已注册",
        "comment": "用户注册状态",
        "key": "1"
    }],
    "isOwner": [{
        "value": "否",
        "comment": "是否是用户自己房产",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否是用户自己房产",
        "key": "1"
    }],
    "prizeUploadFile": [{
        "value": "奖品图片目录",
        "comment": "上传文件目录",
        "key": "prize/"
    }],
    "inviteStatus": [{
        "value": "未注册",
        "comment": "邀请状态",
        "key": "01"
    }, {
        "value": "已注册",
        "comment": "邀请状态",
        "key": "02"
    }],
    "isReceive": [{
        "value": "否",
        "comment": "是否接收通知",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否接收通知",
        "key": "1"
    }],
    "isFocus": [{
        "value": "否",
        "comment": "是否收藏",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否收藏",
        "key": "1"
    }],
    "lotteryStatus": [{
        "value": "未中奖",
        "comment": "抽奖中奖状态",
        "key": "0"
    }, {
        "value": "已中奖未领用",
        "comment": "抽奖中奖状态",
        "key": "1"
    }, {
        "value": "中奖已领用",
        "comment": "抽奖中奖状态",
        "key": "2"
    }],
    "promotionType": [{
        "value": "商家广告",
        "comment": "活动类型",
        "key": "01"
    }, {
        "value": "众筹活动",
        "comment": "活动类型",
        "key": "02"
    }, {
        "value": "缴费活动",
        "comment": "活动类型",
        "key": "03"
    }, {
        "value": "积分抽奖",
        "comment": "活动类型",
        "key": "04"
    }, {
        "value": "启动抽奖",
        "comment": "活动类型",
        "key": "05"
    }, {
        "value": "其他",
        "comment": "活动类型",
        "key": "06"
    }],
    "isRecordSnap": [{
        "value": "否",
        "comment": "是否记录服务快照（服务控制）",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否记录服务快照（服务控制）",
        "key": "1"
    }],
    "msg_statu": [{
        "value": "正常",
        "comment": "信息状态",
        "key": "01"
    }, {
        "value": "暂停",
        "comment": "信息状态",
        "key": "02"
    }, {
        "value": "失效",
        "comment": "信息状态",
        "key": "03"
    }],
    "phoneType": [{
        "value": "快递 ",
        "comment": "便民电话类型",
        "key": "01"
    }, {
        "value": "物业公司 ",
        "comment": "便民电话类型",
        "key": "02"
    }, {
        "value": "居委会 ",
        "comment": "便民电话类型",
        "key": "03"
    }, {
        "value": "业委会 ",
        "comment": "便民电话类型",
        "key": "04"
    }, {
        "value": "送水 ",
        "comment": "便民电话类型",
        "key": "05"
    }, {
        "value": "收废品 ",
        "comment": "便民电话类型",
        "key": "06"
    }, {
        "value": "报修电话 ",
        "comment": "便民电话类型",
        "key": "07"
    }, {
        "value": "开锁换锁 ",
        "comment": "便民电话类型",
        "key": "08"
    }, {
        "value": "其它",
        "comment": "便民电话类型",
        "key": "09"
    }],
    "chargeNo": [{
        "value": "物业费",
        "type": "1",
        "comment": "收费项目",
        "key": "C001"
    }, {
        "value": "车位服务费",
        "type": "1",
        "comment": "收费项目",
        "key": "C002"
    }, {
        "value": "水费",
        "type": "1",
        "comment": "收费项目",
        "key": "C003"
    }, {
        "value": "电费",
        "type": "1",
        "comment": "收费项目",
        "key": "C004"
    }, {
        "value": "煤气费",
        "type": "1",
        "comment": "收费项目",
        "key": "C005"
    }, {
        "value": "清洁费",
        "type": "1",
        "comment": "收费项目",
        "key": "C006"
    }, {
        "value": "二次加压",
        "type": "1",
        "comment": "收费项目",
        "key": "C007"
    }, {
        "value": "水损",
        "type": "1",
        "comment": "收费项目",
        "key": "C008"
    }, {
        "value": "电损",
        "type": "1",
        "comment": "收费项目",
        "key": "C009"
    }, {
        "value": "车位租用费",
        "type": "1",
        "comment": "收费项目",
        "key": "C010"
    }, {
        "value": "电梯维保费",
        "type": "2",
        "comment": "收费项目",
        "key": "C011"
    }, {
        "value": "公共维修资金",
        "type": "2",
        "comment": "收费项目",
        "key": "C012"
    }, {
        "value": "信息服务费",
        "type": "2",
        "comment": "收费项目",
        "key": "C013"
    }, {
        "value": "摊位费",
        "type": "2",
        "comment": "收费项目",
        "key": "C014"
    }, {
        "value": "杂费",
        "type": "2",
        "comment": "收费项目",
        "key": "C015"
    }, {
        "value": "装修履约金",
        "type": "3",
        "comment": "收费项目",
        "key": "C016"
    }, {
        "value": "一键缴费",
        "type": "1",
        "comment": "收费项目",
        "key": "Y001"
    }],
    "sysMessageType": [{
        "value": "提示信息",
        "comment": "服务信息提示类型",
        "key": "1"
    }, {
        "value": "警告信息",
        "comment": "服务信息提示类型",
        "key": "2"
    }, {
        "value": "错误信息",
        "comment": "服务信息提示类型",
        "key": "3"
    }],
    "garageType": [{
        "value": "地上固定",
        "comment": "车位类别",
        "key": "1"
    }, {
        "value": "地下",
        "comment": "车位类别",
        "key": "2"
    }, {
        "value": "地上流动",
        "comment": "车位类别",
        "key": "3"
    }],
    "isallowChange": [{
        "value": "否",
        "comment": "是否允许改价",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否允许改价",
        "key": "1"
    }],
    "isPenalty": [{
        "value": "无",
        "comment": "是否有滞纳金",
        "key": "0"
    }, {
        "value": "有",
        "comment": "是否有滞纳金",
        "key": "1"
    }],
    "returnStatus": [{
        "value": "已退还",
        "comment": "履约金状态",
        "key": "01"
    }, {
        "value": " 已收费",
        "comment": "履约金状态",
        "key": "02"
    }],
    "scriptUploadFile": [{
        "value": "字典脚本路径",
        "comment": "上传文件目录",
        "key": "script/"
    }],
    "isTop": [{
        "value": "否",
        "comment": "置顶标志",
        "key": "0"
    }, {
        "value": "是",
        "comment": "置顶标志",
        "key": "1"
    }, {
        "value": "否",
        "comment": "是否当前最高版本（接口版本控制）",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否当前最高版本（接口版本控制）",
        "key": "1"
    }],
    "communityUploadFile": [{
        "value": "小区俯瞰图目录",
        "comment": "上传文件目录",
        "key": "community/"
    }],
    "controlExpression": [{
        "value": ">",
        "comment": "控制表达式",
        "key": "1"
    }, {
        "value": " =",
        "comment": "控制表达式",
        "key": "2"
    }, {
        "value": "<",
        "comment": "控制表达式",
        "key": "3"
    }],
    "companyState": [{
        "value": "停用",
        "comment": "公司状态",
        "key": "0"
    }, {
        "value": "启用",
        "comment": "公司状态",
        "key": "1"
    }],
    "useType": [{
        "value": "无使用类型限制",
        "comment": "使用类型",
        "key": "00"
    }, {
        "value": "物业费",
        "comment": "使用类型",
        "key": "01"
    }, {
        "value": "车位费",
        "comment": "使用类型",
        "key": "02"
    }, {
        "value": "水费",
        "comment": "使用类型",
        "key": "03"
    }, {
        "value": "电费",
        "comment": "使用类型",
        "key": "04"
    }, {
        "value": "气费",
        "comment": "使用类型",
        "key": "05"
    }, {
        "value": "卫生费",
        "comment": "使用类型",
        "key": "06"
    }, {
        "value": "一键缴费",
        "comment": "使用类型",
        "key": "07"
    }, {
        "value": "其他",
        "comment": "使用类型",
        "key": "08"
    }],
    "businessUploadFile": [{
        "value": "协议附件存放目录",
        "comment": "上传文件目录",
        "key": "business/"
    }],
    "paymentType": [{
        "value": "现金",
        "comment": "支付方式",
        "key": "01"
    }, {
        "value": "刷卡",
        "comment": "支付方式",
        "key": "02"
    }, {
        "value": "转账",
        "comment": "支付方式",
        "key": "03"
    }, {
        "value": "自助缴费",
        "comment": "支付方式",
        "key": "04"
    }],
    "houConstruct": [{
        "value": "木结构",
        "comment": "房屋结构",
        "key": "1"
    }, {
        "value": "砖混结构",
        "comment": "房屋结构",
        "key": "2"
    }, {
        "value": "钢筋混凝土",
        "comment": "房屋结构",
        "key": "3"
    }, {
        "value": "框架结构",
        "comment": "房屋结构",
        "key": "4"
    }, {
        "value": "剪力墙结构",
        "comment": "房屋结构",
        "key": "5"
    }],
    "locType": [{
        "value": "顶部",
        "comment": "广告展示位置类型",
        "key": "0"
    }, {
        "value": "底部",
        "comment": "广告展示位置类型",
        "key": "1"
    }],
    "payerChannel": [{
        "value": "支付宝",
        "comment": "第三方支付渠道",
        "key": "ALIPAY"
    }, {
        "value": "微信",
        "comment": "第三方支付渠道",
        "key": "WECHAT"
    }, {
        "value": "银联支付",
        "comment": "第三方支付渠道",
        "key": "UNIONPAY"
    }],
    "wechatCertUploadFile": [{
        "value": "微信证书上传目录",
        "comment": "上传文件目录",
        "key": "wechatCert/"
    }],
    "preferType": [{
        "value": "红包",
        "comment": "优惠类型",
        "key": "01"
    }, {
        "value": "卡券",
        "comment": "优惠类型",
        "key": "02"
    }, {
        "value": "折扣优惠",
        "comment": "优惠类型",
        "key": "03"
    }],
    "ratingUploadFile": [{
        "value": "等级图标路径",
        "comment": "上传文件目录",
        "key": "rating/"
    }],
    "propertyLevel": [{
        "value": "大众",
        "comment": "业主等级",
        "key": "1"
    }, {
        "value": "白银",
        "comment": "业主等级",
        "key": "2"
    }, {
        "value": "黄金",
        "comment": "业主等级",
        "key": "3"
    }, {
        "value": "铂金",
        "comment": "业主等级",
        "key": "4"
    }, {
        "value": "钻石",
        "comment": "业主等级",
        "key": "5"
    }],
    "pakingTyoe": [{
        "value": "租用",
        "comment": "业主车位类型",
        "key": "0"
    }, {
        "value": "购买",
        "comment": "业主车位类型",
        "key": "1"
    }],
    "isPresent": [{
        "value": "否",
        "comment": "是否可转赠",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否可转赠",
        "key": "1"
    }],
    "houseStatus": [{
        "value": "业主入住",
        "comment": "房屋使用状态",
        "key": "1"
    }, {
        "value": "已出租",
        "comment": "房屋使用状态",
        "key": "2"
    }, {
        "value": "空闲",
        "comment": "房屋使用状态",
        "key": "3"
    }],
    "conStatus": [{
        "value": "未缴纳",
        "comment": "维修基金缴纳状态",
        "key": "0"
    }, {
        "value": "已缴纳",
        "comment": "维修基金缴纳状态",
        "key": "1"
    }],
    "isAttention": [{
        "value": "否",
        "comment": "是否关注",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否关注",
        "key": "1"
    }],
    "isCheckAccess": [{
        "value": "否",
        "comment": "是否检查登录（服务控制）",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否检查登录（服务控制）",
        "key": "1"
    }],
    "complanLogoUploadFile": [{
        "value": "商家logo存放目录",
        "comment": "上传文件目录",
        "key": "complanLogo/"
    }],
    "payingUploadFile": [{
        "value": "缴费凭证目录",
        "comment": "上传文件目录",
        "key": "paying/"
    }],
    "msg_type": [{
        "value": "系统消息",
        "comment": "资讯信息类型",
        "key": "0"
    }, {
        "value": "小区公告消息",
        "comment": "资讯信息类型",
        "key": "1"
    }, {
        "value": "员工消息",
        "comment": "资讯信息类型",
        "key": "2"
    }],
    "ticketStatus": [{
        "value": "未使用",
        "comment": "优惠券状态",
        "key": "0"
    }, {
        "value": "已使用",
        "comment": "优惠券状态",
        "key": "1"
    }, {
        "value": "已过期",
        "comment": "优惠券状态",
        "key": "2"
    }],
    "employeeStatus": [{
        "value": "在职",
        "comment": "员工状态",
        "key": "1"
    }, {
        "value": "离职",
        "comment": "员工状态",
        "key": "2"
    }],
    "chargeWar": [{
        "value": "按户",
        "comment": "计费方式",
        "key": "01"
    }, {
        "value": "按人数",
        "comment": "计费方式",
        "key": "02"
    }, {
        "value": "按建筑面积",
        "comment": "计费方式",
        "key": "03"
    }, {
        "value": "按使用量",
        "comment": "计费方式",
        "key": "04"
    }],
    "userIconUploadFile": [{
        "value": "用户头像存放目录",
        "comment": "上传文件目录",
        "key": "userIcon/"
    }],
    "isFund": [{
        "value": "否",
        "comment": "是否账务类服务（服务控制）",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否账务类服务（服务控制）",
        "key": "1"
    }],
    "terminalState": [{
        "value": "停用",
        "comment": "渠道状态（渠道控制）",
        "key": "0"
    }, {
        "value": "启用",
        "comment": "渠道状态（渠道控制）",
        "key": "1"
    }],
    "familRelate": [{
        "value": "夫妻",
        "comment": "业主房屋常驻成员关系",
        "key": "0"
    }, {
        "value": "父子",
        "comment": "业主房屋常驻成员关系",
        "key": "1"
    }, {
        "value": "父女",
        "comment": "业主房屋常驻成员关系",
        "key": "2"
    }, {
        "value": "母子",
        "comment": "业主房屋常驻成员关系",
        "key": "3"
    }, {
        "value": "母女",
        "comment": "业主房屋常驻成员关系",
        "key": "4"
    }, {
        "value": "兄弟",
        "comment": "业主房屋常驻成员关系",
        "key": "5"
    }, {
        "value": "亲戚",
        "comment": "业主房屋常驻成员关系",
        "key": "6"
    }, {
        "value": "朋友",
        "comment": "业主房屋常驻成员关系",
        "key": "7"
    }],
    "shippingForm": [{
        "value": "按金额",
        "comment": "预缴优惠形式",
        "key": "0"
    }, {
        "value": "按比率",
        "comment": "预缴优惠形式",
        "key": "1"
    }],
    "ticketType": [{
        "value": "代金券",
        "comment": "卡券类型",
        "key": "0"
    }, {
        "value": "折扣券",
        "comment": "卡券类型",
        "key": "1"
    }],
    "prePayWar": [{
        "value": "按周期缴纳",
        "comment": "预缴方式",
        "key": "0"
    }, {
        "value": "按金额缴纳",
        "comment": "预缴方式",
        "key": "1"
    }],
    "approvalStatus": [{
        "value": "未通过",
        "comment": "房屋装修审批状态",
        "key": "0"
    }, {
        "value": "已通过",
        "comment": "房屋装修审批状态",
        "key": "1"
    }],
    "pactionType": [{
        "value": "首次注册",
        "comment": "积分动作编号",
        "key": "001"
    }, {
        "value": "首次登录(仅限业主)",
        "comment": "积分动作编号",
        "key": "002"
    }, {
        "value": "回复公告信息",
        "comment": "积分动作编号",
        "key": "003"
    }, {
        "value": "分享成功",
        "comment": "积分动作编号",
        "key": "004"
    }, {
        "value": "意见反馈",
        "comment": "积分动作编号",
        "key": "005"
    }, {
        "value": "缴费成功",
        "comment": "积分动作编号",
        "key": "006"
    }, {
        "value": "邀请好友成功注册",
        "comment": "积分动作编号",
        "key": "007"
    }, {
        "value": "抽奖",
        "comment": "积分动作编号",
        "key": "008"
    }, {
        "value": "收费（员工收费软件）",
        "comment": "积分动作编号",
        "key": "101"
    }, {
        "value": "兑吧兑换",
        "comment": "积分消耗动作名称",
        "key": "201"
    }, {
        "value": "抽奖消耗",
        "comment": "积分消耗动作名称",
        "key": "202"
    }],
    "isOffset": [{
        "value": "是",
        "comment": "是否冲抵物业费",
        "key": "Y"
    }, {
        "value": "否",
        "comment": "是否冲抵物业费",
        "key": "N"
    }],
    "adType": [{
        "value": "悬浮",
        "comment": "广告展示类型",
        "key": "0"
    }],
    "apartmentUploadFile": [{
        "value": "小区户型图目录",
        "comment": "上传文件目录",
        "key": "apartment/"
    }],
    "staType": [{
        "value": "转账",
        "comment": "对账统计类型",
        "key": "R001"
    }, {
        "value": "现金",
        "comment": "对账统计类型",
        "key": "R002"
    }, {
        "value": "刷卡",
        "comment": "对账统计类型",
        "key": "R003"
    }, {
        "value": "自助缴费",
        "comment": "对账统计类型",
        "key": "R004"
    }, {
        "value": "物业费",
        "comment": "对账统计类型",
        "key": "R005"
    }, {
        "value": "水费",
        "comment": "对账统计类型",
        "key": "R006"
    }, {
        "value": "电费",
        "comment": "对账统计类型",
        "key": "R007"
    }, {
        "value": "其它费用",
        "comment": "对账统计类型",
        "key": "R008"
    }],
    "getStatus": [{
        "value": "未获取成功",
        "comment": "领取奖品状态",
        "key": "0"
    }, {
        "value": "获取成功",
        "comment": "领取奖品状态",
        "key": "1"
    }],
    "cycle": [{
        "value": "1个月",
        "comment": "缴费周期",
        "key": "1"
    }, {
        "value": "2个月",
        "comment": "缴费周期",
        "key": "2"
    }, {
        "value": "3个月",
        "comment": "缴费周期",
        "key": "3"
    }, {
        "value": "4个月",
        "comment": "缴费周期",
        "key": "4"
    }, {
        "value": "5个月",
        "comment": "缴费周期",
        "key": "5"
    }, {
        "value": "6个月",
        "comment": "缴费周期",
        "key": "6"
    }, {
        "value": "7个月",
        "comment": "缴费周期",
        "key": "7"
    }, {
        "value": "8个月",
        "comment": "缴费周期",
        "key": "8"
    }, {
        "value": "9个月",
        "comment": "缴费周期",
        "key": "9"
    }, {
        "value": "10个月",
        "comment": "缴费周期",
        "key": "10"
    }, {
        "value": "11个月",
        "comment": "缴费周期",
        "key": "11"
    }, {
        "value": "12个月",
        "comment": "缴费周期",
        "key": "12"
    }],
    "controlRelation": [{
        "value": "and(且)",
        "comment": "控制关系",
        "key": "1"
    }, {
        "value": "or（或）",
        "comment": "控制关系",
        "key": "2"
    }],
    "isMarried": [{
        "value": "未婚",
        "comment": "婚姻状况",
        "key": "0"
    }, {
        "value": "已婚",
        "comment": "婚姻状况",
        "key": "1"
    }],
    "partyType": [{
        "value": "水费",
        "comment": "在线缴费类型",
        "key": "001"
    }, {
        "value": "电费",
        "comment": "在线缴费类型",
        "key": "002"
    }, {
        "value": "燃气费",
        "comment": "在线缴费类型",
        "key": "003"
    }],
    "reqStatus": [{
        "value": "申请处理中",
        "comment": "房屋装修申请状态",
        "key": "0"
    }, {
        "value": "申请处理失败",
        "comment": "房屋装修申请状态",
        "key": "1"
    }, {
        "value": "申请处理成功",
        "comment": "房屋装修申请状态",
        "key": "2"
    }],
    "status": [{
        "value": "已赞",
        "comment": "邀请状态",
        "key": "01"
    }, {
        "value": "未赞",
        "comment": "邀请状态",
        "key": "02"
    }, {
        "value": "未使用卡券",
        "comment": "卡券状态",
        "key": "01"
    }, {
        "value": "历史卡券",
        "comment": "卡券状态",
        "key": "02"
    }],
    "needChgePwd": [{
        "value": "否",
        "comment": "修改登录密码标志",
        "key": "0"
    }, {
        "value": "是",
        "comment": "修改登录密码标志",
        "key": "1"
    }],
    "paymentStatus": [{
        "value": "未缴",
        "comment": "账单子项缴费状态",
        "key": "01"
    }, {
        "value": "已缴",
        "comment": "账单子项缴费状态",
        "key": "02"
    }],
    "isCheckPSW": [{
        "value": "否",
        "comment": "是否检查服务密码（服务控制）",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否检查服务密码（服务控制）",
        "key": "1"
    }],
    "cardType": [{
        "value": "代金卷",
        "comment": "卡卷类型",
        "key": "0"
    }, {
        "value": "折扣卷",
        "comment": "卡卷类型",
        "key": "1"
    }],
    "lockStatus": [{
        "value": "系统锁定",
        "comment": "锁定状态",
        "key": "1"
    }, {
        "value": "临时锁定",
        "comment": "锁定状态",
        "key": "2"
    }, {
        "value": "登录锁定",
        "comment": "锁定状态",
        "key": "3"
    }],
    "canConsume": [{
        "value": "否",
        "comment": "是否可以消费",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否可以消费",
        "key": "1"
    }],
    "contractStatus": [{
        "value": "已生效",
        "comment": "合同状态",
        "key": "1"
    }, {
        "value": "未生效",
        "comment": "合同状态",
        "key": "2"
    }],
    "isEnabled": [{
        "value": "否",
        "comment": "是否启用(服务控制)",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否启用(服务控制)",
        "key": "1"
    }],
    "isAllowBlank": [{
        "value": "不可为空",
        "comment": "是否必输（报文检查规则）",
        "key": "0"
    }, {
        "value": "可为空",
        "comment": "是否必输（报文检查规则）",
        "key": "1"
    }],
    "flag": [{
        "value": "否",
        "comment": "是否支持物业代收",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否支持物业代收",
        "key": "1"
    }],
    "supplierStatus": [{
        "value": "不正常",
        "comment": "供应商状态",
        "key": "0"
    }, {
        "value": "正常",
        "comment": "供应商状态",
        "key": "1"
    }],
    "isEmailVerify": [{
        "value": "否",
        "comment": "是否邮件验证",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否邮件验证",
        "key": "1"
    }],
    "isReceiving": [{
        "value": "不接收",
        "comment": "是否接收",
        "key": "0"
    }, {
        "value": "接收",
        "comment": "是否接收",
        "key": "1"
    }],
    "buildingType": [{
        "value": "高层",
        "comment": "建筑类型",
        "key": "1"
    }, {
        "value": "小高层",
        "comment": "建筑类型",
        "key": "2"
    }, {
        "value": "多层",
        "comment": "建筑类型",
        "key": "3"
    }, {
        "value": "其他",
        "comment": "建筑类型",
        "key": "4"
    }],
    "useStatus": [{
        "value": "失效",
        "comment": "卡券状态",
        "key": "0"
    }, {
        "value": "正常",
        "comment": "卡券状态",
        "key": "1"
    }],
    "cycleRange": [{
        "value": "不限周期",
        "comment": "积分控制周期",
        "key": "00"
    }, {
        "value": "一次性",
        "comment": "积分控制周期",
        "key": "01"
    }, {
        "value": "每天",
        "comment": "积分控制周期",
        "key": "02"
    }],
    "sex": [{
        "value": "男",
        "comment": "性别",
        "key": "M"
    }, {
        "value": "女",
        "comment": "性别",
        "key": "F"
    }, {
        "value": "未知",
        "comment": "性别",
        "key": "U"
    }],
    "queStatus": [{
        "value": "失效",
        "comment": "问题状态",
        "key": "0"
    }, {
        "value": "有效",
        "comment": "问题状态",
        "key": "1"
    }],
    "aDegree": [{
        "value": "省级",
        "comment": "物业协会级别",
        "key": "1"
    }, {
        "value": "市级",
        "comment": "物业协会级别",
        "key": "2"
    }, {
        "value": "区级",
        "comment": "物业协会级别",
        "key": "3"
    }],
    "isMobileVerify": [{
        "value": "否",
        "comment": "是否手机认证",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否手机认证",
        "key": "1"
    }],
    "isRealNameVerify": [{
        "value": "否",
        "comment": "是否实名验证",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否实名验证",
        "key": "1"
    }],
    "memberDuty": [{
        "value": "主任",
        "comment": "业委会业主职务",
        "key": "1"
    }, {
        "value": "秘书长",
        "comment": "业委会业主职务",
        "key": "2"
    }, {
        "value": "楼栋长",
        "comment": "业委会业主职务",
        "key": "3"
    }, {
        "value": "成员",
        "comment": "业委会业主职务",
        "key": "4"
    }],
    "handleStatus": [{
        "value": "处理成功",
        "comment": "房产证办理状态",
        "key": "0"
    }, {
        "value": "处理失败",
        "comment": "房产证办理状态",
        "key": "1"
    }, {
        "value": "处理中",
        "comment": "房产证办理状态",
        "key": "2"
    }],
    "terminalStatus": [{
        "value": "停用",
        "comment": "公司渠道状态",
        "key": "0"
    }, {
        "value": "启用",
        "comment": "公司渠道状态",
        "key": "1"
    }],
    "checkStatus": [{
        "value": "审核中",
        "comment": "审核状态",
        "key": "1"
    }, {
        "value": "审核成功",
        "comment": "审核状态",
        "key": "2"
    }, {
        "value": "审核失败",
        "comment": "审核状态",
        "key": "3"
    }],
    "isCheckSms": [{
        "value": "否",
        "comment": "是否检查手机验证码（服务控制）",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否检查手机验证码（服务控制）",
        "key": "1"
    }],
    "discounts": [{
        "value": "0.98折",
        "comment": "复核优惠折扣",
        "key": "0.98"
    }, {
        "value": "0.95折",
        "comment": "复核优惠折扣",
        "key": "0.95"
    }, {
        "value": "0.9折",
        "comment": "复核优惠折扣",
        "key": "0.9"
    }, {
        "value": "0.85折",
        "comment": "复核优惠折扣",
        "key": "0.85"
    }, {
        "value": "0.8折",
        "comment": "复核优惠折扣",
        "key": "0.8"
    }],
    "feeType": [{
        "value": "周期性费项",
        "comment": "费项类型",
        "key": "1"
    }, {
        "value": "临时费项",
        "comment": "费项类型",
        "key": "2"
    }, {
        "value": "履约金费项",
        "comment": "费项类型",
        "key": "3"
    }],
    "bpType": [{
        "value": "水卡充值",
        "comment": "代缴类型",
        "key": "01"
    }, {
        "value": "点卡充值",
        "comment": "代缴类型",
        "key": "02"
    }, {
        "value": "账单代缴",
        "comment": "代缴类型",
        "key": "03"
    }],
    "recFlag": [{
        "value": "不推荐",
        "comment": "推荐标志",
        "key": "0"
    }, {
        "value": "推荐",
        "comment": "推荐标志",
        "key": "1"
    }],
    "listType": [{
        "value": "黑名单",
        "comment": "名单类型(黑白名单控制表)",
        "key": "1"
    }, {
        "value": "白名单",
        "comment": "名单类型(黑白名单控制表)",
        "key": "2"
    }],
    "collecType": [{
        "value": "小区公告消息",
        "comment": "收藏类型",
        "key": "0"
    }],
    "degrees": [{
        "value": "小学",
        "comment": "教育程度",
        "key": "01"
    }, {
        "value": "中学",
        "comment": "教育程度",
        "key": "02"
    }, {
        "value": "高中",
        "comment": "教育程度",
        "key": "03"
    }, {
        "value": "中专",
        "comment": "教育程度",
        "key": "04"
    }, {
        "value": "大专",
        "comment": "教育程度",
        "key": "05"
    }, {
        "value": "本科",
        "comment": "教育程度",
        "key": "06"
    }, {
        "value": "研究生",
        "comment": "教育程度",
        "key": "07"
    }, {
        "value": "博士",
        "comment": "教育程度",
        "key": "08"
    }],
    "paymentWay": [{
        "value": "物业代收",
        "comment": "平台三种缴费方式",
        "key": "01"
    }, {
        "value": "在线直缴",
        "comment": "平台三种缴费方式",
        "key": "02"
    }, {
        "value": "人工代缴",
        "comment": "平台三种缴费方式",
        "key": "03"
    }],
    "productState": [{
        "value": "停用",
        "comment": "产品状态（产品信息）",
        "key": "0"
    }, {
        "value": "启用",
        "comment": "产品状态（产品信息）",
        "key": "1"
    }],
    "licenseUploadFile": [{
        "value": "物业公司营业执照",
        "comment": "上传文件目录",
        "key": "license/"
    }],
    "127": [{
        "value": "yw/loginBackImg.png",
        "comment": "公司个性化字典",
        "key": "ywLoginBackImg"
    }, {
        "value": "银湾物业",
        "comment": "公司个性化字典",
        "key": "ywCname"
    }],
    "relatedPType": [{
        "value": "朋友",
        "comment": "用户关系",
        "key": "F"
    }, {
        "value": "亲戚",
        "comment": "用户关系",
        "key": "R"
    }, {
        "value": "同事",
        "comment": "用户关系",
        "key": "C"
    }, {
        "value": "邻居",
        "comment": "用户关系",
        "key": "N"
    }, {
        "value": "其他",
        "comment": "用户关系",
        "key": "O"
    }],
    "propertyType": [{
        "value": "房产持有人",
        "comment": "业主类型",
        "key": "0"
    }, {
        "value": "持有人亲朋",
        "comment": "业主类型",
        "key": "1"
    }, {
        "value": "临时业主",
        "comment": "业主类型",
        "key": "2"
    }, {
        "value": "曾经业主",
        "comment": "业主类型",
        "key": "3"
    }],
    "companyUploadFile": [{
        "value": "物业公司LOGO目录",
        "comment": "上传文件目录",
        "key": "company/"
    }],
    "isProperty": [{
        "value": "否",
        "comment": "是否业主",
        "key": "0"
    }, {
        "value": "是",
        "comment": "是否业主",
        "key": "1"
    }],
    "messageChannel": [{
        "value": "全渠道",
        "comment": "信息收发渠道",
        "key": "00"
    }, {
        "value": "短信",
        "comment": "信息收发渠道",
        "key": "01"
    }, {
        "value": "系统通知",
        "comment": "信息收发渠道",
        "key": "02"
    }, {
        "value": "微信",
        "comment": "信息收发渠道",
        "key": "03"
    }, {
        "value": "微博",
        "comment": "信息收发渠道",
        "key": "04"
    }, {
        "value": "QQ",
        "comment": "信息收发渠道",
        "key": "05"
    }, {
        "value": "其他",
        "comment": "信息收发渠道",
        "key": "06"
    }],
    "relativesType": [{
        "value": "妻子",
        "comment": "亲属关系",
        "key": "1"
    }, {
        "value": "丈夫",
        "comment": "亲属关系",
        "key": "2"
    }, {
        "value": "儿子",
        "comment": "亲属关系",
        "key": "3"
    }, {
        "value": "女儿",
        "comment": "亲属关系",
        "key": "4"
    }, {
        "value": "父亲",
        "comment": "亲属关系",
        "key": "5"
    }, {
        "value": "母亲",
        "comment": "亲属关系",
        "key": "6"
    }, {
        "value": "兄长",
        "comment": "亲属关系",
        "key": "7"
    }, {
        "value": "弟弟",
        "comment": "亲属关系",
        "key": "8"
    }, {
        "value": "姐姐",
        "comment": "亲属关系",
        "key": "9"
    }, {
        "value": "妹妹",
        "comment": "亲属关系",
        "key": "10"
    }],
    "questionStatus": [{
        "value": "失效",
        "comment": "问题状态",
        "key": "0"
    }, {
        "value": "有效",
        "comment": "问题状态",
        "key": "1"
    }],
    "chargeType": [{
        "value": "周期性缴费",
        "comment": "缴费类型",
        "key": "01"
    }, {
        "value": "临时性收费",
        "comment": "缴费类型",
        "key": "02"
    }, {
        "value": "履约金收费",
        "comment": "缴费类型",
        "key": "03"
    }, {
        "value": "非业主收费",
        "comment": "缴费类型",
        "key": "04"
    }, {
        "value": " 一键缴/收费",
        "comment": "缴费类型",
        "key": "05"
    }, {
        "value": " 履约金退还",
        "comment": "缴费类型",
        "key": "06"
    }, {
        "value": "在线缴费",
        "comment": "缴费类型",
        "key": "07"
    }, {
        "value": "人工代缴",
        "comment": "缴费类型",
        "key": "08"
    }, {
        "value": "履约金退还抵充",
        "comment": "缴费类型",
        "key": "09"
    }]
};
